### ISSUE TITLE
[Bug]  Remote Jackett Support

### ISSUE THREAD

**Issue by zero77** [BoredLama/stremio-jackett-addon#4] opened 2019-02-27 13:33 UTC
Can you please add support to connect to a remote Jackett server outside of LAN.
Thanks

**Comment by BoredLama** [comment] 2019-02-27 13:44
This is already supported, following the thread of tickets created for requesting and perfecting this:
https://github.com/BoredLama/stremio-jackett-addon/issues/1 , https://github.com/BoredLama/stremio-jackett-addon/issues/2 , https://github.com/BoredLama/stremio-jackett-addon/issues/3

There is also a guide written on making it work remotely:
https://www.reddit.com/r/StremioAddons/comments/aqxdge/guide_using_local_addons_remotely_on_other_devices/

The way this works is that it creates a `localtunnel`, it has been reported that this tunnel can crash, the released version also has code written to restart the tunnel if it crashes, but i've been unable to reproduce the issue in my tests to make sure it works.

So if you do this, please read these comments too: https://github.com/BoredLama/stremio-jackett-addon/issues/3#issuecomment-438693281

And tell me if you see the tunnel crashing and restarting correctly, as it's important to know if the fix works or not.

**Comment by zero77** [comment] 2019-02-27 14:02
@BoredLama 
Thanks, i will have a look and get back to you after i have had a chance to test.

**Comment by zero77** [comment] 2019-02-27 14:49
I can install the addon with the localtunnel.me link and it works ok.
But, when searching for a film it seams to just crash with out any errors and nothing else hapens.

Is there a debuging option or a log file.

this is the config i am using 
```{
    // if this is set to true, the add-on will run on system start-up
    "autoLaunch": false,
    // for stremio add-on, in milliseconds, if timeout is reached it will respond with whatever results it already has, 0 = no timeout
    "responseTimeout": 11000,
    // port to use for stremio add-on, default is 7000
    "addonPort": 7000,
    // remove torrents with less then X seeds
    "minimumSeeds": 3,
    // maximum number of torrents to respond with, 0 = no limit
    "maximumResults": 15,
    // make add-on available remotely too, through LAN and the Internet
    "remote": true,
    // set the preferred subdomain (if available), only applicable if remote is set to true
    "subdomain": "sgaerhyaqeh",
    "jackett": {
        // self explanatory, the default port is presumed
        "host": "http://remote-ip:port/",
        // read timeout in milliseconds for http requests to jackett server, 0 = no timeout
        "readTimeout": 10000,
        // open timeout in milliseconds for http requests to jackett server, 0 = no timeout
        "openTimeout": 10000
    }
}
```

**Comment by BoredLama** [comment] 2019-02-27 16:38
Your config seems ok, it should always log everything important, let me try to test it a bit myself, if i can't reproduce it I'll try to add more logs so we can find out where it's failing for you.

Thanks for helping

**Comment by BoredLama** [comment] 2019-02-27 17:16
I've just tested this on OSX and it seems to work fine to search remotely for me, are you sure you're using the latest (v1.0.4) `stremio-jackett-addon` from here:
https://github.com/BoredLama/stremio-jackett-addon/releases

What operating system are you using?

**Comment by BoredLama** [comment] 2019-02-27 17:18
And what do you mean by:
> just crash with out any errors

Does the add-on application close? Or does Stremio just have the loading animation for a long time?

**Comment by zero77** [comment] 2019-02-27 17:28
I am definitely using the latest one and i am using ubuntu 18.04 both locally and remotely where jacket 0.10.842.0 is installed.

The output is like this then it closes, without anything else.
> ./stremio-jackett-linux-x64
Add-on URL: http://127.0.0.1:7000/[my-jackett-key]/manifest.json
Remote Add-on URL: https://sgaerhyaqeh.localtunnel.me/[my-jackett-key]/manifest.json
Replace "[my-jackett-key]" with your Jackett API Key

**Comment by BoredLama** [comment] 2019-03-04 11:10
I've just release v1.0.5, you can download it from here:
https://github.com/BoredLama/stremio-jackett-addon/releases

I wasn't able to reproduce or make a probable fix for your issue, but I added a new error log somewhere that might be the reason to why it didn't show the error for your case.

So please test it in the same circumstances and tell me if it shows an error now.

**Comment by zero77** [comment] 2019-03-05 13:09
@BoredLama 
I tried out the new release and this time i got an error before it closed.

```
Error: Protocol "magnet:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:131:11)
    at Object.request (http.js:38:10)
    at simpleGet (/snapshot/stremio-jackett-addon-master 3/node_modules/simple-get/index.js:47:24)
    at ClientRequest.protocol.request.res (/snapshot/stremio-jackett-addon-master 3/node_modules/simple-get/index.js:59:19)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
```
Also, on a separate note can you add a version argument (-v) that displays the current version then exits.
Because, i think this could help to quickly determine what version you are using.
Thanks

**Comment by BoredLama** [comment] 2019-03-05 14:50
Made a new release (v1.0.6):
https://github.com/BoredLama/stremio-jackett-addon/releases

It adds `-v` and a possible fix for ur scenario, test it out.

**Comment by zero77** [comment] 2019-03-05 14:54
Thanks and i will test it out now.

**Comment by zero77** [comment] 2019-03-05 15:04
Its working now thanks and so it -v.

**Comment by BoredLama** [comment] 2019-03-05 15:19
The reason for this issue has not yet been resolved.

Please test it for a week or so, try to leave the tunnel open as long as possible, check if the tunnel fails and paste the logs pls.

**Comment by zero77** [comment] 2019-03-05 15:22
Ok, i will let you know if there are any other problems.

**Comment by BoredLama** [comment] 2019-03-14 11:54
any news on this, yet?

**Comment by zero77** [comment] 2019-03-15 14:37
It still seems to be working ok after the update.

**Comment by BoredLama** [comment] 2019-03-18 12:52
cool, i'm closing this issue then, please keep monitoring it.

if you see anything wrong with it please open a new issue.

**Closed as completed by BoredLama** 2019-03-18 12:52 UTC

**Comment by zero77** [comment] 2019-03-18 13:27
Ok, thanks.
