### ISSUE TITLE
Localtunnel restart if closed

### ISSUE THREAD

**Issue by eded333** [BoredLama/stremio-jackett-addon#3] opened 2018-11-11 19:10 UTC
I'm finding localtunnel a bit unstable, so as a workaround I found a script to restart the tunnel if it closes (running localtunnel as a global app), here is the link:
https://github.com/localtunnel/localtunnel/issues/81#issuecomment-218320442
Its for ruby, not sure if you will be able to implement something similar on node.js, but it would be a welcome enhancement.

**Comment by BoredLama** [comment] 2018-11-14 15:04
I don't see any use for the ruby code, and i'm not interacting with localtunnel's binary directly, I'm using the node module made for it:
https://www.npmjs.com/package/localtunnel
(their github link goes to the same repo you posted though)

How does the add-on react when the localtunnel closes? does the add-on itself also close or not?

I'm asking because I'm currently listening to a `close` event from the tunnel, and the add-on is made to close itself also if the tunnel closes. If the add-on doesn't close itself too though, then it means that the `close` event isn't firing.

There's also an `error` event that I'm not listening to at all, if the `error` event fires in these cases and the `close` event doesn't, then I could restart localtunnel from it's `error` event. Do you know of any way to make a test scenario for this? In how much time from running the add-on does the localtunnel usually fail?

**Comment by eded333** [comment] 2018-11-14 19:59
The ruby script restarts the tunnel if the tunnel closes, the script itself keeps running. I'll monitor my rig but it seems that the tunnel crashes every 6 hours or less. This is the output the script gives:

```
Running localtunnel for the 1st time
/usr/lib/node_modules/localtunnel/bin/client:65
        throw err;
        ^

Error: connection refused: localtunnel.me:46401 (check your firewall settings)
    at Socket.<anonymous> (/usr/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Running localtunnel for the 2nd time
```

**Comment by BoredLama** [comment] 2019-02-15 11:52
Hi, I'm sorry it took so long to respond to this. I did research it to find out that this is a common `localtunnel` issue.

When the tunnel server is considered to be flooded, it disconnects some users and shows them that error, they also don't seem to have any interest in fixing the issue.

I've also encountered the issue myself since then, but also tried to wait for it to happen in order to test a probable fix, and it never happened for days..

With that said, I released a version that has a possible (yet untested) fix. What it does is that it listens to any error from the local tunnel, and if it gets an error it closes the tunnel, waits 30 seconds and tries again.

The issue here is that sometimes (from what i've read in my research), the tunnel server can get "stuck" on your previously selected subdomain, so it won't allow it to be used again for some time. It is for this reason that the possible fix also includes a check to see if the new localtunnel url has the requested subdomain set, if it doesn't, it will close the tunnel again, and attempt again in 30 seconds, and so on, until it gets the requested subdomain too.

The logic should work, but unless it is reproducible on your side, we'll never really know.. so please test this when you can. There will be logs that state if it gets disconnected, if it's reconnecting, if the expected subdomain isn't correct, etc.

This new version also includes an `autoLaunch` parameter in `config.json`, which if set to `true` would run the add-on on system start-up. It would be helpful if you can test this too.

You can download the binaries for v1.0.4 from here:
https://github.com/BoredLama/stremio-jackett-addon/releases

I hope your still interested in helping with this and will hear from you soon.

**Comment by eded333** [comment] 2019-02-17 01:39
Great! Thanks for the update, I'll try it this week and let you know how it goes and post the logs.

**Comment by BoredLama** [comment] 2019-02-26 16:04
any news on this yet?

**Comment by BoredLama** [comment] 2019-03-14 11:55
ping
u still around? got a chance to test this yet?

**Comment by BoredLama** [comment] 2019-03-18 12:53
I'm presuming that this works and closing it.

If you see anything wrong with it please open a new issue.

**Closed as completed by BoredLama** 2019-03-18 12:53 UTC
